import type { Metadata } from "next";
import { FC, ReactNode } from "react";

import { Navbar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Art Paradise",
  description: "Generated by create next app",
};

interface RootLayoutProp {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProp> = ({ children }) => {
  return (
    <div>
      <Navbar />
      {children}
    </div>
  );
};

export default RootLayout;
